import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { AuthLayout } from "@/components/auth/AuthLayout";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { appConfig } from "@/config/app.config";
import { supabase } from "@/integrations/supabase/client";
import { formatBrazilianPhone, maximumBirthDate, profileSchema } from "@/lib/auth/identity";
import { completeProfile } from "@/lib/auth/profile.functions";

type LegalVersion = { id: string; document_type: string };
export const Route = createFileRoute("/complete-profile")({ ssr: false, head: () => ({ meta: [{ title: `Complete seu perfil | ${appConfig.name}` }, { name: "description", content: "Complete seus dados de acesso ao Gestor da Sorte." }, { property: "og:title", content: `Complete seu perfil | ${appConfig.name}` }, { property: "og:description", content: "Complete seus dados para continuar." }, { property: "og:type", content: "website" }, { name: "robots", content: "noindex" }, { name: "twitter:card", content: "summary" }] }), component: CompleteProfilePage });
function CompleteProfilePage() {
  const navigate = useNavigate(); const save = useServerFn(completeProfile); const [name, setName] = useState(""); const [birthDate, setBirthDate] = useState(""); const [phone, setPhone] = useState(""); const [accepted, setAccepted] = useState(false); const [versions, setVersions] = useState<LegalVersion[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { Promise.all([supabase.auth.getUser(), supabase.from("profiles").select("display_name,birth_date,phone").maybeSingle(), supabase.from("legal_document_versions").select("id,document_type").eq("is_active", true)]).then(([, profile, legal]) => { if (profile.data) { setName(profile.data.display_name ?? ""); setBirthDate(profile.data.birth_date ?? ""); setPhone(formatBrazilianPhone(profile.data.phone ?? "")); } setVersions((legal.data ?? []) as LegalVersion[]); }); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!accepted) { setError("Aceite os documentos vigentes para continuar"); return; } const parsed = profileSchema.safeParse({ name, birthDate, phone, acceptedDocumentIds: versions.map((item) => item.id) }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Confira seus dados"); return; } setLoading(true); try { await save({ data: { ...parsed.data, phone: parsed.data.phone ?? "" } }); navigate({ to: "/dashboard", replace: true }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar seus dados"); } finally { setLoading(false); } }
  async function signOut() { await supabase.auth.signOut(); navigate({ to: "/login", replace: true }); }
  return <AuthLayout title="Complete seu perfil" description="Precisamos confirmar sua maioridade e os dados essenciais antes de continuar."><form onSubmit={submit} className="space-y-4"><Field label="Nome completo" id="profile-name"><Input id="profile-name" required maxLength={120} value={name} onChange={(e) => setName(e.target.value)} className="h-11" /></Field><div className="grid grid-cols-[minmax(0,1fr)] gap-4 sm:grid-cols-2"><Field label="Data de nascimento" id="profile-birth"><Input id="profile-birth" type="date" max={maximumBirthDate()} required value={birthDate} onChange={(e) => setBirthDate(e.target.value)} className="h-11" /></Field><Field label="Telefone" id="profile-phone"><Input id="profile-phone" type="tel" required value={phone} onChange={(e) => setPhone(formatBrazilianPhone(e.target.value))} className="h-11" /></Field></div><label className="flex cursor-pointer items-start gap-3 text-sm text-text-secondary"><Checkbox checked={accepted} onCheckedChange={(value) => setAccepted(value === true)} className="mt-0.5 size-5" /><span>Li e aceito os <Link to="/terms" target="_blank" className="text-primary underline">Termos de Uso</Link> e a <Link to="/privacy" target="_blank" className="text-primary underline">Política de Privacidade</Link> vigentes.</span></label>{error ? <p className="text-sm text-danger" role="alert">{error}</p> : null}<Button className="h-11 w-full" disabled={loading}>{loading ? "Salvando…" : "Salvar e continuar"}</Button><Button type="button" variant="ghost" className="w-full" onClick={signOut}>Sair</Button></form></AuthLayout>;
}
function Field({ label, id, children }: { label: string; id: string; children: React.ReactNode }) { return <div className="min-w-0 space-y-1.5"><Label htmlFor={id}>{label}</Label>{children}</div>; }
