import { createFileRoute } from "@tanstack/react-router";
import { Brand } from "@/components/brand/Brand";
import { PublicFooter } from "@/components/public/PublicFooter";
import { appConfig } from "@/config/app.config";
export const Route = createFileRoute("/privacy")({ head: () => ({ meta: [{ title: `Política de Privacidade | ${appConfig.name}` }, { name: "description", content: "Política preliminar de privacidade do Gestor da Sorte." }, { property: "og:title", content: `Política de Privacidade | ${appConfig.name}` }, { property: "og:description", content: "Saiba como o Gestor da Sorte trata dados pessoais e arquivos." }, { property: "og:type", content: "article" }, { property: "og:url", content: `${appConfig.canonicalOrigin}/privacy` }, { name: "twitter:card", content: "summary" }], links: [{ rel: "canonical", href: `${appConfig.canonicalOrigin}/privacy` }] }), component: PrivacyPage });
const sections = [
["1. Escopo", "Esta política descreve o tratamento de dados no Gestor da Sorte, ferramenta de organização de jogos, bolões, concursos e resultados. Ela não representa revisão jurídica definitiva."],
["2. Dados coletados", "Tratamos nome, data de nascimento, telefone, e-mail, avatar, dados de autenticação fornecidos pelo provedor, preferências, jogos, bolões, participantes, pagamentos informativos, arquivos, imagens e comprovantes inseridos pelo usuário. Senhas não são armazenadas em nossos perfis ou registros."],
["3. Finalidades", "Nome identifica sua conta; nascimento confirma a maioridade; telefone permite contato e prepara futura verificação, sem OTP nesta fase; e-mail permite autenticação, confirmação e recuperação segura; arquivos e dados de jogos e bolões entregam as funções solicitadas."],
["4. Autenticação e terceiros", "Usamos serviços necessários de hospedagem, banco de dados, armazenamento, autenticação e login Google. Esses prestadores processam dados apenas para viabilizar o serviço e aplicam suas próprias medidas e termos."],
["5. Compartilhamento público", "O organizador pode criar links públicos de participantes, jogos ou visão completa. Quem possui o link poderá acessar os dados publicados naquele escopo, inclusive comprovantes marcados como públicos. O organizador controla a criação, substituição e revogação desses links."],
["6. Segurança e minimização", "Aplicamos controles de acesso por usuário, armazenamento privado quando previsto, links temporários e validações no servidor. Coletamos apenas dados necessários às finalidades apresentadas. Nenhum sistema é totalmente imune a incidentes, e adotaremos medidas proporcionais quando necessário."],
["7. Menores de idade", "O Gestor da Sorte é destinado exclusivamente a maiores de 18 anos. A data de nascimento é obrigatória e validada no cadastro e no servidor. Não buscamos tratar intencionalmente dados de menores."],
["8. Retenção e exclusão", "Dados permanecem enquanto a conta ou a finalidade estiver ativa e pelo período necessário para segurança, obrigações aplicáveis e integridade de registros. Recursos de exclusão removem os dados conforme as regras disponíveis, respeitando retenções técnicas ou legais aplicáveis."],
["9. Direitos e contato", "Você poderá solicitar acesso, correção, atualização e exclusão de dados quando aplicável. Responsável: Gestor da Sorte. O canal institucional para essas solicitações ainda será definido antes da publicação da versão jurídica definitiva."],
["10. Versões", "Novas versões serão registradas separadamente. Quando uma mudança exigir novo aceite, o sistema solicitará confirmação antes da continuidade do uso autenticado."],
];
function PrivacyPage(){return <div className="min-h-screen bg-background"><header className="border-b border-border bg-surface"><div className="mx-auto max-w-4xl px-4 py-4"><Brand /></div></header><main className="mx-auto max-w-4xl px-4 py-10"><p className="text-xs font-semibold uppercase text-warning">Versão preliminar para homologação jurídica · versão 1.0</p><h1 className="mt-3 font-display text-3xl font-semibold text-text-primary">Política de Privacidade</h1><p className="mt-3 text-sm text-text-secondary">Última atualização: 12 de setembro de 2026.</p><div className="mt-8 space-y-8">{sections.map(([title,body])=><section key={title}><h2 className="font-display text-lg font-semibold text-text-primary">{title}</h2><p className="mt-2 leading-7 text-text-secondary">{body}</p></section>)}</div><p className="mt-10 border-t border-border pt-5 text-sm font-semibold text-warning">Versão preliminar — sujeita à revisão jurídica.</p></main><PublicFooter /></div>}
