import { createFileRoute } from "@tanstack/react-router";
import { Brand } from "@/components/brand/Brand";
import { PublicFooter } from "@/components/public/PublicFooter";
import { appConfig } from "@/config/app.config";
export const Route = createFileRoute("/terms")({ head: () => ({ meta: [{ title: `Termos de Uso | ${appConfig.name}` }, { name: "description", content: "Termos preliminares de uso do Gestor da Sorte." }, { property: "og:title", content: `Termos de Uso | ${appConfig.name}` }, { property: "og:description", content: "Conheça as condições preliminares de uso do Gestor da Sorte." }, { property: "og:type", content: "article" }, { property: "og:url", content: `${appConfig.canonicalOrigin}/terms` }, { name: "twitter:card", content: "summary" }], links: [{ rel: "canonical", href: `${appConfig.canonicalOrigin}/terms` }] }), component: TermsPage });
const sections = [
["1. Finalidade", "O Gestor da Sorte é uma ferramenta de organização e acompanhamento de jogos, bolões, concursos, resultados, comprovantes e informações históricas. Não comercializamos apostas, não recebemos valores para realizá-las e não atuamos como lotérica ou intermediador."],
["2. Elegibilidade e conta", "O uso de conta é destinado a pessoas com 18 anos ou mais. Você deve informar dados verdadeiros, proteger suas credenciais e comunicar qualquer uso não autorizado. Contas Google seguem também as regras de autenticação do Google."],
["3. Jogos, geração e estatísticas", "Recursos de geração organizam combinações por filtros, critérios matemáticos e preferências estatísticas. Histórico e estatísticas não preveem resultados futuros, não alteram as probabilidades matemáticas e não garantem premiação."],
["4. Bolões e compartilhamento", "O serviço permite organizar participantes, cotas, pagamentos informativos, jogos, comprovantes, relatórios e links públicos. O organizador é responsável pelo conteúdo e por compartilhar links somente com as pessoas adequadas. O Gestor da Sorte não recebe pagamentos do bolão nem realiza apostas."],
["5. Dados e arquivos", "Você é responsável por possuir autorização para inserir nomes, telefones, imagens, comprovantes e demais dados de terceiros. Links públicos podem tornar visíveis as informações selecionadas pelo organizador a qualquer pessoa que possua o endereço."],
["6. Disponibilidade e fontes", "Resultados e concursos dependem de sincronização com fontes externas. Buscamos apresentar informações consistentes, mas podem ocorrer atrasos, indisponibilidades ou correções. Confirme sempre os resultados e comprovantes pelos canais oficiais."],
["7. Uso responsável", "É proibido usar o serviço para fraude, violação de direitos, acesso indevido ou publicação de conteúdo ilegal. Podemos adotar medidas de segurança e restringir acessos abusivos conforme necessário para proteger o serviço e seus usuários."],
["8. Alterações e contato", "Estes termos poderão receber novas versões. Quando uma alteração exigir novo aceite, o sistema solicitará sua confirmação. Responsável: Gestor da Sorte. O canal institucional de contato ainda será definido antes da publicação da versão jurídica definitiva."],
];
function TermsPage(){return <div className="min-h-screen bg-background"><header className="border-b border-border bg-surface"><div className="mx-auto max-w-4xl px-4 py-4"><Brand /></div></header><main className="mx-auto max-w-4xl px-4 py-10"><p className="text-xs font-semibold uppercase text-warning">Versão preliminar para homologação jurídica · versão 1.0</p><h1 className="mt-3 font-display text-3xl font-semibold text-text-primary">Termos de Uso</h1><p className="mt-3 text-sm text-text-secondary">Última atualização: 12 de setembro de 2026.</p><div className="mt-8 space-y-8">{sections.map(([title,body])=><section key={title}><h2 className="font-display text-lg font-semibold text-text-primary">{title}</h2><p className="mt-2 leading-7 text-text-secondary">{body}</p></section>)}</div><p className="mt-10 border-t border-border pt-5 text-sm font-semibold text-warning">Versão preliminar — sujeita à revisão jurídica.</p></main><PublicFooter /></div>}
