/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedContestsIndexRouteImport } from './routes/_authenticated/contests.index'
import { Route as AuthenticatedContestsIdRouteImport } from './routes/_authenticated/contests.$id'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games.index'
import { Route as AuthenticatedGamesIdRouteImport } from './routes/_authenticated/games.$id'
import { Route as AuthenticatedPoolsIndexRouteImport } from './routes/_authenticated/pools.index'
import { Route as AuthenticatedPoolsIdRouteImport } from './routes/_authenticated/pools.$id'
import { Route as AuthenticatedPoolsNewRouteImport } from './routes/_authenticated/pools.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContestsIndexRoute =
  AuthenticatedContestsIndexRouteImport.update({
    id: '/contests/',
    path: '/contests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContestsIdRoute = AuthenticatedContestsIdRouteImport.update({
  id: '/contests/$id',
  path: '/contests/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesIdRoute = AuthenticatedGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoolsIndexRoute = AuthenticatedPoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoolsIdRoute = AuthenticatedPoolsIdRouteImport.update({
  id: '/pools/$id',
  path: '/pools/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoolsNewRoute = AuthenticatedPoolsNewRouteImport.update({
  id: '/pools/new',
  path: '/pools/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/more': typeof AuthenticatedMoreRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/contests/$id': typeof AuthenticatedContestsIdRoute
  '/games/$id': typeof AuthenticatedGamesIdRoute
  '/pools/$id': typeof AuthenticatedPoolsIdRoute
  '/pools/new': typeof AuthenticatedPoolsNewRoute
  '/contests/': typeof AuthenticatedContestsIndexRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/pools/': typeof AuthenticatedPoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/more': typeof AuthenticatedMoreRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/contests/$id': typeof AuthenticatedContestsIdRoute
  '/games/$id': typeof AuthenticatedGamesIdRoute
  '/pools/$id': typeof AuthenticatedPoolsIdRoute
  '/pools/new': typeof AuthenticatedPoolsNewRoute
  '/contests': typeof AuthenticatedContestsIndexRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/pools': typeof AuthenticatedPoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/contests/$id': typeof AuthenticatedContestsIdRoute
  '/_authenticated/games/$id': typeof AuthenticatedGamesIdRoute
  '/_authenticated/pools/$id': typeof AuthenticatedPoolsIdRoute
  '/_authenticated/pools/new': typeof AuthenticatedPoolsNewRoute
  '/_authenticated/contests/': typeof AuthenticatedContestsIndexRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/pools/': typeof AuthenticatedPoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/generate'
    | '/more'
    | '/notifications'
    | '/profile'
    | '/results'
    | '/settings'
    | '/statistics'
    | '/contests/$id'
    | '/games/$id'
    | '/pools/$id'
    | '/pools/new'
    | '/contests/'
    | '/games/'
    | '/pools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/generate'
    | '/more'
    | '/notifications'
    | '/profile'
    | '/results'
    | '/settings'
    | '/statistics'
    | '/contests/$id'
    | '/games/$id'
    | '/pools/$id'
    | '/pools/new'
    | '/contests'
    | '/games'
    | '/pools'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/generate'
    | '/_authenticated/more'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/results'
    | '/_authenticated/settings'
    | '/_authenticated/statistics'
    | '/_authenticated/contests/$id'
    | '/_authenticated/games/$id'
    | '/_authenticated/pools/$id'
    | '/_authenticated/pools/new'
    | '/_authenticated/contests/'
    | '/_authenticated/games/'
    | '/_authenticated/pools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contests/': {
      id: '/_authenticated/contests/'
      path: '/contests'
      fullPath: '/contests/'
      preLoaderRoute: typeof AuthenticatedContestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contests/$id': {
      id: '/_authenticated/contests/$id'
      path: '/contests/$id'
      fullPath: '/contests/$id'
      preLoaderRoute: typeof AuthenticatedContestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/$id': {
      id: '/_authenticated/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AuthenticatedGamesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pools/': {
      id: '/_authenticated/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof AuthenticatedPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pools/$id': {
      id: '/_authenticated/pools/$id'
      path: '/pools/$id'
      fullPath: '/pools/$id'
      preLoaderRoute: typeof AuthenticatedPoolsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pools/new': {
      id: '/_authenticated/pools/new'
      path: '/pools/new'
      fullPath: '/pools/new'
      preLoaderRoute: typeof AuthenticatedPoolsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedContestsIdRoute: typeof AuthenticatedContestsIdRoute
  AuthenticatedGamesIdRoute: typeof AuthenticatedGamesIdRoute
  AuthenticatedPoolsIdRoute: typeof AuthenticatedPoolsIdRoute
  AuthenticatedPoolsNewRoute: typeof AuthenticatedPoolsNewRoute
  AuthenticatedContestsIndexRoute: typeof AuthenticatedContestsIndexRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedPoolsIndexRoute: typeof AuthenticatedPoolsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedContestsIdRoute: AuthenticatedContestsIdRoute,
  AuthenticatedGamesIdRoute: AuthenticatedGamesIdRoute,
  AuthenticatedPoolsIdRoute: AuthenticatedPoolsIdRoute,
  AuthenticatedPoolsNewRoute: AuthenticatedPoolsNewRoute,
  AuthenticatedContestsIndexRoute: AuthenticatedContestsIndexRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedPoolsIndexRoute: AuthenticatedPoolsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
